/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Windowing;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @org.junit.jupiter.api.Test
    void appHasAGreeting() {
        TestMe classUnderTest = new TestMe();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
