/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Windowing;

import Windowing.datastructure.PrioritySearchTree;

import java.util.ArrayList;
import java.util.Arrays;

public class TestMe {
    public static void main(String[] args) {
        ArrayList<Double> data = new ArrayList<>(Arrays.asList(1D, 5D, 9D, 7D));
        PrioritySearchTree tree = PrioritySearchTree.createPrioritySearchTree(data);
        System.out.println("");
    }
}
